config/urls.py
from django.contrib import admin
from django.urls import path

from mysite.views import BlogListView
from mysite.views import BlogDetailView
from mysite.views import BlogCrateView
from mysite.views import BlogDeleteView
from mysite.views import BlogUpdateView
from mysite.views import BlogCategoryView
from mysite.views import BlogTemplateView

from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', BlogListView.as_view(), name='index'),
    path('<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('create', BlogCrateView.as_view(), name='create'),
    path('<int:pk>/delete', BlogDeleteView.as_view(), name='delete'),
    path('<int:pk>/update', BlogUpdateView.as_view(), name='update'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('category/<int:pk>', BlogCategoryView.as_view(), name='category'),
    path('about', BlogTemplateView.as_view(template_name='blog_about.html'), name='about'),
]

mysite/models.py
from django.db import models

from django.utils.html import mark_safe
from markdown import markdown


class Category(models.Model):
    """カテゴリ"""
    name = models.CharField(max_length=250, verbose_name='カテゴリ')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='作成日')

    def __str__(self):
        return self.name


class Blog(models.Model):
    """ブログの記事"""
    title = models.CharField(max_length=250, verbose_name='タイトル')
    content = models.TextField(verbose_name='本文')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='作成日')
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)

    def get_content_as_markdown(self):
        return mark_safe(markdown(self.content, safe_mode='escape'))

    def __str__(self):
        return self.title

mysite/forms.py
from django import forms

from .models import Blog


class BlogForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'size': 100}))
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 100}))
    category = forms.ChoiceField

    class Meta:
        model = Blog
        fields = ['title', 'content', 'category']

mysite/views.py
from django.db.models import Q
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import get_object_or_404

from .models import Blog, Category
from .forms import BlogForm


class BlogListView(generic.ListView):
    model = Blog
    context_object_name = 'blogs'
    paginate_by = 10

    def get_queryset(self):
        """降順"""
        queryset = Blog.objects.order_by('-created_at')
        """キーワード検索"""
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(content__icontains=keyword))
        return queryset


class BlogDetailView(generic.DetailView):
    model = Blog
    context_object_name = 'blog'


class BlogCrateView(generic.CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        """記事を投稿した時に表示するメッセージ"""
        messages.success(self.request, '保存しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '保存に失敗しました')
        return super().form_invalid(form)


class BlogDeleteView(generic.DeleteView):
    model = Blog
    success_url = reverse_lazy('index')


class BlogUpdateView(generic.UpdateView):
    model = Blog
    form_class = BlogForm

    def get_success_url(self):
        return reverse_lazy('detail', kwargs={'pk': self.kwargs['pk']})


class BlogCategoryView(generic.ListView):
    model = Blog
    paginate_by = 10
    context_object_name = 'blogs'

    def get_queryset(self):
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        queryset = Blog.objects.order_by('-created_at').filter(category=category)
        return queryset


class BlogTemplateView(generic.TemplateView):
    model = Blog

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- fontawesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <title>Note to self</title>
    </head>
    <body>
        <!-- ナビバーここから -->
        <div class="container" style="border-bottom: 1px solid #333">
            <nav class="navbar navbar-expand-lg navbar-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                        <!--カテゴリ-->
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Category</a>
                        <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 38px, 0px);">
                            {% for category in category_list %}
                            <a class="dropdown-item" href="{% url 'category' category.pk %}">{{ category }}</a>
                            {% endfor %}
                        </div>
                    </li>
                    </ul>
                    <!--検索-->
                    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'index' %}">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" name="keyword">
                    </form>
                    <!--ログアウト-->
                    {% if user.is_authenticated %}
                    <div class="logout">
                        <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt btn btn-outline-secondary"></i></a>
                    </div>
                    {% endif %}
                </div>
            </nav>
        </div>
        <!-- ナビバーここまで -->
        <!-- サイトタイトルここから -->
        <div class="container title">
            <h1 class="animated fadeIn"><a href="{% url 'index' %}">Note to self</a></h1>
        </div>
        <!-- サイトタイトルここまで -->
        <!-- フラッシュメッセージ -->
        {% if messages %}
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-unstyled">
                        {% for message in messages %}
                        <li class="bg-{%if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert">
                        {{message}}
                            <button type="button" class="close" aria-label="Close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}
        <!--フラッシュメッセージここまで-->

        {% block body %}
        {%  endblock %}

        <footer>
            <p>&#169; 2018 Note to self ALL RIGHTS RESERVED.</p>
        </footer>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

mysite/templates/blog_about.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="card mb-3 text-center border-secondary mx-auto">
            <div class="card-body">
                <blockquote class="card-blockquote">
                    <p>このサイトはWEBアプリの勉強のため、DjangoとBootstrapを使用して作成しました。</p>
                </blockquote>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/templates/mysite/blog_confirm_delete.html
{% extends 'base.html' %}

{% block body %}

        <div class="container">
            <div class="text-center">
                <h2>削除の確認</h2>
                <h3>{{ blog.title }}</h3>
                <p>削除してもよろしいですか？</p>
                <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-danger">削除</button>
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">キャンセル</a>
                </form>
            </div>
        </div>

{% endblock %}

mysite/templates/mysite/blog_detail.html
{% extends 'base.html' %}


{% block body %}
        {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto mb-4">
                    <a href="{% url 'update' blog.pk %}" class="btn btn-outline-secondary">編集</a>
                    <a href="{% url 'delete' blog.pk %}" class="btn btn-danger">削除</a>
                </div>
            </div>
        </div>
        {% endif %}

        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2 mx-auto" style="font-family: 'Hiragino Kaku Gothic ProN','ヒラギノ角ゴ ProN W3','メイリオ', Meiryo,sans-serif;">
                    <div class="card">
                        <div class="card-header">
                            <h1>{{ blog.title }}</h1>
                        </div>
                        <div class="card-body">
                            <blockquote class="card-blockquote">
                                <p style="font-size: 18px">{{ blog.get_content_as_markdown }}</p>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

mysite/templates/mysite/blog_form.html
{% extends 'base.html' %}

{% block body %}
        <div class="container">
            <h2>新規作成</h2>
            <form method="POST">
                {% csrf_token %}
                <table class="table">
                    {{ form }}
                </table>
                <button type="submit" class="btn btn-outline-primary">送信</button>
            </form>
        </div>
{% endblock %}

mysite/templates/mysite/blog_list.html
{% extends 'base.html' %}

{% block body %}
        <!--新規作成ボタン-->
        {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <a href="{% url 'create' %}" class="btn btn-block btn-outline-secondary">New</a>
                </div>
            </div>
        </div>
        {% endif %}
        <!--新規作成ボタンここまで-->
        <!-- 記事ここから -->
        {% for blog in blogs %}
        <div class="container post">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-preview">
                        <h2 class="post-title">
                            {{ blog.title }}
                        </h2>
                        <p>{{ blog.created_at|date:"Y-m-d" }} {{ blog.category }}
                        <a href="{% url 'detail' blog.pk %}" class="btn btn-outline-secondary">Read more</a>
                        </p>
                    </div>
                </div>
            </div>
            <hr>
        </div>
        {% endfor %}
        <!--記事ここまで-->

        <!--前へ-->
        {% if page_obj.has_previous %}
        <div class="container">
            <div class="paging">
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-secondary">前へ</a>
            </div>
        </div>
                {% endif %}
                <!--次へ-->
        <div class="container">
            <div class="paging">
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-secondary">次へ</a>
            </div>
        </div>
        {% endif %}

{% endblock %}